
#ifndef CONSTANT_H
#define CONSTANT_H

#define WIDTH_SCREEN 800
#define HEIGHT_SCREEN 600
#define DIVIDER_TITLE_POSITION_Y 35

#define WIDTH_TABLE_SCREEN (WIDTH_SCREEN - 1)
#define TABLE_SCREEN_POSITION_Y1 (DIVIDER_TITLE_POSITION_Y + 2)

#define MATRIX_GAME_WIDHT 160
#define MATRIX_GAME_HEIGHT 112

#endif