
#ifndef CONSTANT_H
#define CONSTANT_H

#define WIDTH_SCREEN 1280
#define HEIGHT_SCREEN 720
#define DIVIDER_TITLE_POSITION_Y 35
#define SIZE_SQUARE 10

#define WIDTH_TABLE_SCREEN (WIDTH_SCREEN - 1)
#define TABLE_SCREEN_POSITION_Y1 (DIVIDER_TITLE_POSITION_Y + 2)

#define MATRIX_GAME_WIDHT (WIDTH_SCREEN / SIZE_SQUARE)
#define MATRIX_GAME_HEIGHT ((HEIGHT_SCREEN - DIVIDER_TITLE_POSITION_Y) / SIZE_SQUARE)

#endif